### ISSUE TITLE
[Bug]: Install piexif using apt

### ISSUE THREAD

**Issue by alex-arnal** [RobotnikAutomation/image_metadata_writer#2]
### What happened?

We had issues to generate libraries when the package depends on python modules that are installed via pip. In this case _piexif_. We should install this module via apt.

**Comment by alex-arnal** [comment]
https://ubuntu.pkgs.org/22.04/ubuntu-universe-arm64/python3-piexif_1.1.3-2_all.deb.html

**Comment by rafa-martin** [comment]
just accepted rosdistro pr https://github.com/ros/rosdistro/pull/43253, and this pr into this repo: https://github.com/RobotnikAutomation/image_metadata_writer/pull/1 so, this issue is done
